export const PRODUCT_LIST_REQUEST = "PRODUCT_LIST_REQUEST";
export const PRODUCT_LIST_SUCCESS = "PRODUCT_LIST_SUCCESS";
export const PRODUCT_LIST_FAIL = "PRODUCT_LIST_FAIL";

export const PRODUCT_LIST_PROTIEN_REQUEST = "PRODUCT_LIST_PROTIEN_REQUEST";
export const PRODUCT_LIST_PROTIEN_SUCCESS = "PRODUCT_LIST_PROTIEN_SUCCESS";
export const PRODUCT_LIST_PROTIEN_FAIL = "PRODUCT_LIST_PROTIEN_FAIL";

export const PRODUCT_LIST_GAINER_REQUEST = "PRODUCT_LIST_GAINER_REQUEST";
export const PRODUCT_LIST_GAINER_SUCCESS = "PRODUCT_LIST_GAINER_SUCCESS";
export const PRODUCT_LIST_GAINER_FAIL = "PRODUCT_LIST_GAINER_FAIL";

export const PRODUCT_LIST_ISORICH_REQUEST = "PRODUCT_LIST_ISORICH_REQUEST";
export const PRODUCT_LIST_ISORICH_SUCCESS = "PRODUCT_LIST_ISORICH_SUCCESS";
export const PRODUCT_LIST_ISORICH_FAIL = "PRODUCT_LIST_ISORICH_FAIL";

export const PRODUCT_DETAIL_REQUEST = "PRODUCT_DETAIL_REQUEST";
export const PRODUCT_DETAIL_SUCCESS = "PRODUCT_DETAIL_SUCCESS";
export const PRODUCT_DETAIL_FAIL = "PRODUCT_DETAIL_FAIL";



export const CART_ADD_ITEM = "CART_ADD_ITEM";
export const CART_REMOVE_ITEM = "CART_REMOVE_ITEM";
export const CART_FAIL_ITEM = "CART_FAIL_ITEM";


export const USER_LOGIN_REQUEST ="USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS ="USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL ="USER_LOGIN_FAIL";
export const USER_LOGIN_LOGOUT ="USER_LOGIN_LOGOUT";


export const USER_REGISTER_REQUEST ="USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS ="USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL ="USER_REGISTER_FAIL";


export const USER_DETAILS_REQUEST ="USER_REGISTER_REQUEST";
export const USER_DETAILS_SUCCESS ="USER_REGISTER_SUCCESS";
export const USER_DETAILS_RESET = "USER_DETAILS_RESET";
export const USER_DETAILS_FAIL ="USER_REGISTER_FAIL";
